variables:

  # Global
  ap_vm_image: windows-2019

  location: eastus 
  prefix: sa32
  postfix: jh64
  environment: dev

  # Azure DevOps 
  ado_service_connection_rg: Azure-ARM-Dev-SAPA


  # IaC
  baseName: $(prefix)$(postfix)$(environment)
  resourceGroupName: P5-$(baseName)-RG #You also need to change the ResourceGroupname in main.bicep file
  sqlServerName: $(prefix)-sql-$(postfix)-$(environment)
  synapseWorkspace: $(prefix)-synapse-$(postfix)-$(environment)
  synapsedatalakegen2name: $(prefix)adlssyn$(postfix)$(environment)
